[project]
name = "porterstemmingalgorithm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "nltk>=3.9.1",
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

